version: '3.8'

services:
  linux-do-analyzer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DENO_DIR=/deno-dir/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:8080').then(r => r.status === 200 ? Deno.exit(0) : Deno.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linux-do-analyzer.rule=Host(`localhost`)"
      - "traefik.http.services.linux-do-analyzer.loadbalancer.server.port=8080"

  # 可选：使用 Nginx 作为反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - linux-do-analyzer
    restart: unless-stopped
    profiles:
      - nginx

networks:
  default:
    driver: bridge